apiVersion: v1
entries:
  kminion:
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2021-02-20T20:50:19.415433168Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache Kafka
    digest: e277e976d864b4bd2e505038dd865a9300486ae8c4323d3f0be40b84df75732b
    name: kminion
    type: application
    urls:
    - kminion-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2021-02-20T20:50:19.413654762Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache Kafka
    digest: 562937d3613624c55984e51adbc6765e7898d1cf8cc2d7d241b6d671bbc12303
    name: kminion
    type: application
    urls:
    - kminion-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2021-02-20T20:50:19.412703458Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache Kafka
    digest: 25e83d7c7cc92a63268d76b13ecc13077758b48be093490f281498a4f55ad3ca
    name: kminion
    type: application
    urls:
    - kminion-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2021-02-20T20:50:19.41061055Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache Kafka
    digest: 7c10e9d9957e9752bc6f4b4a1fffb742d88cd57be06bf4f26ff7b5031645ccbd
    name: kminion
    type: application
    urls:
    - kminion-0.1.0.tgz
    version: 0.1.0
generated: "2021-02-20T20:50:19.409166745Z"
