name: Build Docker image

on:
  push:
    tags:
      - "*"
    branches:
      - "!master"
      - "**"
    paths-ignore:
      - "charts/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: quay.io/cloudhut/kminion
          tags: |
            type=sha,prefix={{branch}}-

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: cloudhut+github_push
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          build-args: |
            KMINION_VERSION=sha-${{ github.sha }}
